name: Create S3 State File Bucket

on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
        type: string
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
        type: string
      se_bucket_name:
        description: 'S3 bucket name'
        default: "devcloudx-tf-aws-s3-bucket"
        required: true
        type: string  # <-- fixed indentation and typo

jobs:
  create_s3_bucket:
    runs-on: ubuntu-latest

    env:  # ✅ moved to correct location
      AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: aws-s3-statefile-store

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="se_bucket_name=${{ inputs.se_bucket_name }}"
        working-directory: aws-s3-statefile-store
