name: Create AWS EC2 Key Pair using tearrform

on:
  workflow_dispatch:
    inputs:
      AWS_ACCESS_KEY_ID:
        description: "AWS Access Key ID"
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: "AWS Secret Access Key"
        required: true
      KEY_NAME:
        description: "EC2 Key Pair Name"
        required: true

jobs:
  create-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: aws-keypair

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="aws_access_key=${{ github.event.inputs.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_key=${{ github.event.inputs.AWS_SECRET_ACCESS_KEY }}" \
            -var="key_name=${{ github.event.inputs.KEY_NAME }}"
        working-directory: aws-keypair

      - name: Save private key to PEM file
        run: terraform output -raw private_key_pem > private_key.pem
        working-directory: aws-keypair

      - name: Install Putty Tools
        run: sudo apt-get update && sudo apt-get install -y putty-tools

      - name: Convert PEM to PPK
        run: puttygen aws-keypair/private_key.pem -o private_key.ppk

      - name: Upload PPK Artifact
        uses: actions/upload-artifact@v4 #version updated
        with:
          name: ec2-keypair-${{ github.run_id }}
          path: private_key.ppk
