name: Create AWS Security Group (Firewall)

on:
  workflow_dispatch:
    inputs:
      aws_access_key:
        description: 'AWS Access Key ID'
        required: true
      aws_secret_key:
        description: 'AWS Secret Access Key'
        required: true
      security_group_name:
        description: 'Security Group Name'
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_aws_access_key: ${{ github.event.inputs.aws_access_key }}
          TF_VAR_aws_secret_key: ${{ github.event.inputs.aws_secret_key }}
          TF_VAR_security_group_name: ${{ github.event.inputs.security_group_name }}
